apiVersion : apps/v1
kind: Deployment
metadata:
  name: jspinkubdemo 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jspinkubdemo
      track: stable
  template:
    metadata:
      labels:
        app: jspinkubdemo 
        track: stable
    spec:
      containers:
        - name: jspinkubdemo 
          image: devopsheroes.azurecr.io/jspinkubdemo
          ports:
          - containerPort: 80
